// Code generated by "stringer -type RuleType -linecomment -output rule-type_string.go"; DO NOT EDIT.

package n4tosrv6

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RuleTypeUplink-0]
	_ = x[RuleTypeDownlink-1]
	_ = x[RuleTypeDownlinkForwarding-2]
}

const _RuleType_name = "uplinkdownlinkdownlink-forwarding"

var _RuleType_index = [...]uint8{0, 6, 14, 33}

func (i RuleType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_RuleType_index)-1 {
		return "RuleType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RuleType_name[_RuleType_index[idx]:_RuleType_index[idx+1]]
}
